### ISSUE TITLE
Error with instructions

### ISSUE THREAD

**Issue by Barnier-Maxime** [Shimwell/openmc_workshop#2]
I saw a few minor errors with the README.md file

please update link to slide 5 for task 1

**Comment by Shimwell** [comment]
Thanks for spotting this and thanks even more for the pull request #3 

@Barnier-Maxime 

Let me know if you spot any more

**Comment by Barnier-Maxime** [comment]
Just a small error in the program '1_example_isotope_plot.py'

please change the temperature to 294K (and not 293K as written on the program'

**Comment by Barnier-Maxime** [comment]
I think there is another error in the program '3_example_material_plot.py'

the unit of the macroscopic cross section is not 1/cm2 but 1/cm

**Comment by Barnier-Maxime** [comment]
The same error than before : the link to slide 6 in task 2 is the slide 14

**Comment by Barnier-Maxime** [comment]
Another small error is in task 2 you forgot to put the .py at the end of "coder 1_example_geometry_viewer_2d_fortran_version"

**Comment by Barnier-Maxime** [comment]
Hi 
As you told me tomorrow here are the errors on the programs of the task 3 :

2_plot_neutron_birth_location.py :

len(sp.source(['r']['x'])) and len(sp.source(['u']['x'])) line 67 and 68
'x':sp.source['r']['x'][0:2] for the filling of traces

**Comment by Shimwell** [comment]
> Just a small error in the program '1_example_isotope_plot.py'
> 
> please change the temperature to 294K (and not 293K as written on the program'

This has now been fixed, thanks for letting me know

**Comment by Shimwell** [comment]
> I think there is another error in the program '3_example_material_plot.py'
> 
> the unit of the macroscopic cross section is not 1/cm2 but 1/cm

thanks , this is now fixed

**Comment by Shimwell** [comment]
> slide 6

thanks, this is now fixed

**Comment by Shimwell** [comment]
> 1_example_geometry_viewer_2d_fortran_version

thanks this is now fixed
